version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kartingrm
      MYSQL_USER: kartuser
      MYSQL_PASSWORD: kartpass
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    image: xsh1ft/kartingrm-backend:latest
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_MAIL_USERNAME: youremail@gmail.com
      SPRING_MAIL_PASSWORD_FILE: /run/secrets/mail_password
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kartingrm
      SPRING_DATASOURCE_USERNAME: kartuser
      SPRING_DATASOURCE_PASSWORD: kartpass
    secrets:
      - mail_password

  frontend:
    image: xsh1ft/kartingrm-frontend:latest
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  dbdata:

secrets:
  mail_password:
    file: ./secrets/mail_password.txt
