version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kartingrm
      MYSQL_USER: kartuser
      MYSQL_PASSWORD: kartpass
    volumes:
      - dbdata:/var/lib/mysql

  # --- BACK-END, 3 réplicas ---
  backend1: &backend
    image: xsh1ft/kartingrm-backend:latest
    environment: &db_env
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kartingrm
      SPRING_DATASOURCE_USERNAME: kartuser
      SPRING_DATASOURCE_PASSWORD: kartpass
    depends_on: [db]
    expose: ["8080"]

  backend2: *backend
  backend3: *backend

  nginx-backend:
    image: nginx:stable-alpine
    depends_on: [backend1, backend2, backend3]
    volumes:
      - ./nginx-backend.conf:/etc/nginx/conf.d/default.conf:ro
    expose: ["80"]

  # --- FRONT-END, 3 réplicas ---
  frontend1: &frontend
    image: xsh1ft/kartingrm-frontend:latest
    depends_on: [nginx-backend]
    expose: ["80"]

  frontend2: *frontend
  frontend3: *frontend

  nginx-frontend:
    image: nginx:stable-alpine
    depends_on: [frontend1, frontend2, frontend3]
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8070:80"

volumes:
  dbdata:
