pipeline {
    agent any

    stages {
        stage("Build Frontend") {
            steps {
                checkout scmGit(
                    branches: [[name: '*/main']],
                    extensions: [],
                    userRemoteConfigs: [[
                        url: 'https://github.com/xshift007/karting.git'
                    ]]
                )
                dir("kartingrm-frontend") {
                    bat "npm ci"
                    bat "npm run build"
                }
            }
        }

        stage("Build & Push Docker Image") {
            steps {
                dir("kartingrm-frontend") {
                    script {
                        withDockerRegistry('https://index.docker.io/v1/', 'docker-credentials') {
                            // construyo con el número de build...
                            bat "docker build -t xsh1ft/kartingrm-frontend:${env.BUILD_NUMBER} ."
                            bat "docker push xsh1ft/kartingrm-frontend:${env.BUILD_NUMBER}"
                            // y luego retagueo y empujo latest
                            bat "docker tag xsh1ft/kartingrm-frontend:${env.BUILD_NUMBER} xsh1ft/kartingrm-frontend:latest"
                            bat "docker push xsh1ft/kartingrm-frontend:latest"
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
